# Generated by Django 2.1.5 on 2019-02-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_aboutcompany_certificate_recommendation_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutcompany',
            options={'verbose_name': 'About company', 'verbose_name_plural': 'About company'},
        ),
    ]
